FROM golang:1.24 AS builder

ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=arm64

WORKDIR /app
COPY go.mod ./
COPY go.sum ./
RUN go mod download
COPY . .

RUN go build -o /auth_server ./cmd/auth_server

FROM scratch
COPY --from=builder /auth_server /auth_server
COPY .env .env
ENTRYPOINT ["/auth_server"]
