FROM golang:1.24 AS builder

ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=arm64

WORKDIR /app
COPY go.mod ./
COPY go.sum ./
RUN go mod download
COPY . .

RUN go build -o /bin/note_server ./cmd/note_server

FROM scratch
COPY --from=builder /bin/note_server /bin/note_server
COPY .env .env
ENTRYPOINT ["/bin/note_server"]
