FROM golang:1.24 AS builder

ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=arm64

WORKDIR /app
COPY go.mod ./
COPY go.sum ./
RUN go mod download
COPY . .

RUN go build -o /bin/migrate ./cmd/migrate

FROM scratch
COPY --from=builder /bin/migrate /bin/migrate
COPY ./migrations ./migrations
COPY .env .env
ENTRYPOINT ["/bin/migrate"]
